### PR TITLE
Wowhead tooltips

### LINKED ISSUE #6: Add Wowhead tooltips
It may add value for some users to see Wowhead tooltips on item hover (ref https://www.wowhead.com/tooltips).

### PR DESCRIPTION
**Pull request by RolfKoenders**
Nice project! Found it through reddit. Had a bit of time available and always wanted to play with wowhead tooltips, din't know it was that easy tbh.

- Added the wowhead tooltips according to their documentation. 
- Created a component for the Script tags for the `<head />` section
- Removed the wowhead image since this will be replaced by the wowhead icon
- Tried to play around with the styles to make it look good, but this needs a bit more work

<details>
<summary>Screenshots</summary>
Screenshot 2024-05-22 at 14 58 27
Screenshot 2024-05-22 at 14 58 39
Screenshot 2024-05-22 at 14 58 52
</details>

### Todo 
- [ ] Fix styling

### CODE REVIEW

**Comment by continentaldivide** [comment]
Hi Rolf, thanks so much for checking out the project and making some contributions!  To be candid, being a junior, I'm still a little shell shocked to have a project with real users I need to support as a dev, let alone one with contributors I need to support as a maintainer.  I have a branch in progress I want to get merged today or tomorrow before anything else goes in, but I'm enthusiastic to integrate your contributions as soon as I can afterwards.  In the meantime, I wanted to at least let you know I've got eyes on your contributions.

It's both good and bad news that contributions to the app are going to push me outside my comfort zone in terms of git collaboration workflows -- I need the practice, but I apologize in advance for any clumsy steps while I'm figuring things out.  🙂

Thanks again very much for looking at the project, and I'll follow up soon on this, #18, and your comment in #13.  👍

**Comment by RolfKoenders** [comment]
Thanks for the reply and no rush at all! Take your time! It can be quite intimidating or stressful when outside contributors are creating pull requests / issues and might have expectations. 

I'm always down for a chat or discussion of an open issue!

**Comment by continentaldivide** [comment]
Hi @RolfKoenders, hope you're having a great weekend!  Finally got some traction on this today thankfully.  #18 looks great and I've merged that into the dev branch for release 1.0.1.

This PR is off to a good start and I'm pleasantly surprised to see how straightforward it is to implement the tooltips.  While I was tinkering with the styling, I noticed a frustrating issue -- it seems like the script does not play well with collapsing/expanding vendors.  Since it runs only once on initial page load, icons won't appear for vendors that were closed on load, or even vendors that are open on load after a collapse -> expand.

If you're interested in taking another stab at this to resolve that problem while I'm getting 1.0.1 wrapped up, I'd love to include this feature in 1.0.2.  And if not, I still appreciate you giving me a headstart on the feature and will circle back to it soon.  🙂

**Comment by RolfKoenders** [comment]
Heey @continentaldivide, My weekend was great thank you! Hope you had a good one as well! 

Hmm interesting, the script probably does a initial scan on page load and does not keep looking for new ids or changes. I will try to see if I can come up with something!

**Pull request closed without merging**
